bundles:
  - 9
files:
  - source: /Ios
    ignore:
      - /**/*.swift
    translation: Ios/%two_letters_code%/%file_name%
    multilingual: 1
    type: string_catalog
    update_option: update_without_changes
  - source: '/Android'
    ignore:
      - /**/*.swift
    translation: /app/L10N/src/main/res/values-%two_letters_code%/strings.xml
    type: xml
    update_option: update_without_changes
