bundles:
  - 9
files:
  - source: /Ios/**/**/*.xcstrings
    ignore:
      - /**/*.swift
    translation: /%original_path%/%original_file_name%
    multilingual: 1
    type: string_catalog
    update_option: update_without_changes
  - source: /Backend/Glossary/**/en/*.json
    ignore:
      - /**/*.swift
    translation: /Backend/Glossary/**/%two_letters_code%/%original_file_name%
    type: json
    update_option: update_as_unapproved
  - source: '/Android'
    ignore:
      - /**/*.swift
    translation: /app/L10N/src/main/res/values-%two_letters_code%/strings.xml
    type: xml
    update_option: update_without_changes
